# Generated by Django 4.0.4 on 2022-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
